In [1]:
import numpy as np

In [3]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
fives = np.array([5 for i in range(1,11)])
print(fives)

[5 5 5 5 5 5 5 5 5 5]


In [13]:
print(np.arange(10,51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [17]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.randint(0,100,25)

array([31, 47,  1, 50, 76, 47, 49, 74, 70,  9, 48, 33, 10, 90, 28, 11, 26,
       92, 62, 54, 37, 71, 40,  8, 32])