In [1]:
import numpy as np



In [39]:
# Create a numpy array from a list
my_list = [1, 2, 3]
myArr = np.array(my_list)
myArr

array([1, 2, 3])

In [33]:
# List of Lists 
mat = [[1 ,2 ,3], [2, 3, 4], [6, 4, 3]]
np.array(mat)

array([[1, 2, 3],
       [2, 3, 4],
       [6, 4, 3]])

In [37]:
# Creating arrays using build_in functions
# Return evenly spaced values within a given interval
# start, stop, step

np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [51]:
# Arrays of zeros or ones
print(np.zeros(3), np.ones(3))
print(np.zeros((3, 3)))

[0. 0. 0.] [1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
# Return evenly space numbes over a specified intervval
# Start , Stop, number of elements(and not step)
# Unlike numpy.arange(), the stop value is includedi n the result
# The spacing between values is automatically determined based on the specified number of values(num)

print(np.linspace(0, 10, 3))
print(np.linspace(0, 5, 20))
print(np.linspace(0, 5, 21))

[ 0.  5. 10.]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]




### arange: Specify the step/gap between consecutive elements
### linspace : specify how many elements we want .... Step/gap will be calculated by NumPy



In [58]:
# Random number arrays
print(np.random.rand(2))
print(np.random.rand(2, 2))

[0.05594528 0.15035176]
[[0.30272557 0.39019089]
 [0.99955348 0.83921406]]


In [63]:
# Random number from low(inclusive_ to high (exclusive)
print(np.random.randint(1, 100)) # single random integer between 1 and 100
print(np.random.randint(1, 100, 10)) # 10 random number

63
[68 39 41 64 40 24 57 68 93 16]


In [73]:
# Seeding for reproducable results
# -> Generates unpredictable random numbers every single time.
np.random.seed(17)
print(np.random.rand(4))

[0.294665   0.53058676 0.19152079 0.06790036]


In [77]:
# Storing 
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[22 31  4 39 20 44  7  1 46 17]


In [82]:
# reshape: Returns an array containing the same data with a new shape
print(arr.reshape(5, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [86]:
# Max, Min and their index positions
print(ranarr.max())
print(ranarr.argmax())
print(ranarr.min())
print(ranarr.argmin())

46
8
1
7


In [90]:
# Creating sample array
arr = np.arange(0, 11)
print(arr)

# Bracket indexing and selection = similar to python Lists
# Get a value at an index
print(arr[8])
# Get values in a range
print(arr[1:5])

# Broadcasting
# Setting a value with index range(Broadcasting)
arr[0:5] = 100
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[1 2 3 4]
[100 100 100 100 100   5   6   7   8   9  10]


In [95]:
# Reset array
arr = np.arange(0, 11)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [104]:
# Important notes on Slices
slice_of_arr = arr[0:6]
print(slice_of_arr)



[0 1 2 3 4 5]


In [116]:
# Change Slice
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)
# Changes made are also there in our original array!
# Data is not copied, it is a view of the original array! 
# This avoids memory problems.

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [114]:
# To get actual copy, we need .copy method()

In [122]:
# Conditional selection
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [124]:
# Check each element of the array against the condition 
# Which returns a boolean array where
# each element is True if the corresponding element in a 
# and False otherwise
print(arr > 4)

[False False False False  True  True  True  True  True  True]


In [128]:
#Store boolean results in another array
bool_arr = arr > 4
print(bool_arr)

[False False False False  True  True  True  True  True  True]


In [ ]:
#

In [130]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [134]:
#Basic arithmetic
print(arr + arr)
print(arr * arr)
print(arr - arr)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0 0]


In [136]:
# This will raise a Warning on division by zwero, but not an error!
# It just fills the spot with nan
print(arr/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\DAI.STUDENTSDC\AppData\Local\Temp\ipykernel_6932\3063241360.py:3: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)


In [140]:
#Also a warning (but not an error) relating to infinity
print(1/arr)

print(arr**3)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
[  0   1   8  27  64 125 216 343 512 729]


C:\Users\DAI.STUDENTSDC\AppData\Local\Temp\ipykernel_6932\2045597170.py:2: RuntimeWarning: divide by zero encountered in divide
  print(1/arr)


In [142]:
# Universal functions
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\DAI.STUDENTSDC\AppData\Local\Temp\ipykernel_6932\2448541471.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [144]:
# Summary Statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())

45
4.5
9
0
8.25
2.8722813232690143


In [146]:
# 2D arrays
# This is a 2-dimensional array with 3 rows and 4 columns
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [148]:
# Row and column count                   Important in data analytics
print(arr_2d.shape)
# Sum all the columns for each row (e.g. 1+5_9, 2+6+10, etc)
print(arr_2d.shape)
#Sum all the rows for each coloumn (e.g. 1+2+3+4,  5+6+7+8. etc)
print(arr_2d.sum(axis = 1))

(3, 4)
(3, 4)
[10 26 42]
