In a classification problem

if category_A is 50% and category_B is 50%, it is balanced classification problem (in case of multiple classes, it is equally destributed across all the categories)

else the problem is imbalanced classification problem

##### Iris dataset

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import make_column_transformer
from sklearn.compose import make_column_selector
from sklearn.preprocessing import OneHotEncoder, LabelEncoder


In [8]:
iris = pd.read_csv("iris.csv")
X = iris.drop("Species", axis = 'columns')
y = iris['Species']

In [ ]:
ohe = OneHotEncoder()


In [34]:
lbl = LabelEncoder()
y = lbl.fit_transform(y)

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 24, test_size = 0.3)

In [55]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)


In [57]:
confusion_matrix(y_test, y_pred)

array([[15,  0,  0],
       [ 0, 11,  1],
       [ 0,  0, 18]], dtype=int64)

In [59]:
accuracy_score(y_test, y_pred)

0.9777777777777777

##### Default dataset

In [158]:

default = pd.read_csv("Default.csv")
default.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   default  10000 non-null  object 
 1   student  10000 non-null  object 
 2   balance  10000 non-null  float64
 3   income   10000 non-null  float64
dtypes: float64(2), object(2)
memory usage: 312.6+ KB


In [166]:
default['default'] = LabelEncoder().fit_transform(default['default'])
default['default'].unique()

array([0, 1], dtype=int64)

In [168]:
default['student'] = LabelEncoder().fit_transform(default['student'])
default['student'].unique()

array([0, 1], dtype=int64)

In [172]:
mn, mx = default.balance.min(), default.balance.max()
default.balance = default.balance.apply(lambda x : (x - mn) / (mx - mn))


In [174]:
mn, mx = default.income.min(), default.income.max()
default.income = default.income.apply(lambda x : (x - mn) / (mx - mn))

In [176]:
default

default  student   balance    income
0           0        0  0.274845  0.598905
1           0        1  0.307868  0.155727
2           0        0  0.404453  0.425862
3           0        0  0.199392  0.479959
4           0        0  0.295991  0.517867
...       ...      ...       ...       ...
9995        0        0  0.268074  0.717488
9996        0        0  0.285558  0.259524
9997        0        0  0.318504  0.795031
9998        0        0  0.591115  0.493213
9999        0        1  0.075696  0.221084

[10000 rows x 4 columns]

In [180]:
X = default.drop('default', axis = 'columns')
y = default['default']

In [184]:
x_train, x_test, y_train, y_test = train_test_split(X, y, random_state = 24, test_size = 0.3)

In [186]:
log = LogisticRegression()
log.fit(x_train, y_train)
y_pred = log.predict(x_test)


In [188]:
accuracy_score(y_test, y_pred)


0.97

In [192]:
confusion_matrix(y_test, y_pred)

array([[2893,    8],
       [  82,   17]], dtype=int64)

In [ ]:
# Naive model

In [194]:
y.value_counts()

default
0    9667
1     333
Name: count, dtype: int64

In [196]:
9667 / (9667 + 333)

0.9667

##### K-fold cross validation

In [202]:

result = cross_val_score(LogisticRegression(), X, y)
result.mean()

0.9718

##### Wine dataset

In [5]:
wine = pd.read_csv("wine.csv")

In [11]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Class            178 non-null    int64  
 1   Alcohol          178 non-null    float64
 2   Malic            178 non-null    float64
 3   Ash              178 non-null    float64
 4   Alcalinity       178 non-null    float64
 5   Magnesium        178 non-null    int64  
 6   Phenols          178 non-null    float64
 7   Flavanoids       178 non-null    float64
 8   Nonflavanoid     178 non-null    float64
 9   Proanthocyanins  178 non-null    float64
 10  Intensity        178 non-null    float64
 11  Hue              178 non-null    float64
 12  OD280            178 non-null    float64
 13  Proline          178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [212]:
X = wine.drop("Class", axis = 'columns')
y = wine.Class

In [216]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 24, test_size = 0.3)

In [218]:
log = LogisticRegression()
log.fit(X_train, y_train)
y_pred = log.predict(X_test)


C:\Users\DAI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [220]:
accuracy_score(y_test, y_pred)

0.9074074074074074