In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 10, size = (3, 3))
arr

array([[2, 4, 2],
       [7, 6, 9],
       [2, 9, 7]])

In [3]:
eig_val, eig_vec = np.linalg.eig(arr)
eig_val, eig_vec

(array([17.27034949,  1.52544407, -3.79579356]),
 array([[-0.26967132, -0.69938384,  0.32470898],
        [-0.69758608, -0.25153714, -0.75519738],
        [-0.66381552,  0.66902265,  0.56942164]]))

In [11]:
arr3 = np.concatenate((eig_vec, np.array([eig_val]).transpose()), axis = 1)
arr3

array([[-0.26967132, -0.69938384,  0.32470898, 17.27034949],
       [-0.69758608, -0.25153714, -0.75519738,  1.52544407],
       [-0.66381552,  0.66902265,  0.56942164, -3.79579356]])

In [12]:
np.savetxt('myfile_eigenvector.txt', arr3)