In [1]:
import numpy as np

#### Finding version and build configuration of Numpy 

In [3]:
np.version.version

'1.26.4'

In [11]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/DAI.STUDENTSDC/AppData/Local/anaconda3/Library/include
    lib directory: C:/Users/DAI.STUDENTSDC/AppData/Local/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family

#### getting help on add function

In [29]:
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### Numpy program to test whether none of the leements of given array is zero

In [32]:
q3_arr = np.array([2, 3, 4, 5 ,6 , 7])
q3_arr2 = np.array([1, 0, 3, 5, 7, 9])
all(q3_arr != 0), all(q3_arr2 != 0)

(True, False)

#### Test whether any of the elements of  given array is non-zero

In [36]:
q4_a1 = np.zeros(5)
q4_a2 = np.array([0, 0, 2, 0, 0])
any(q4_a1 != 0), any(q4_a2 != 0)

(False, True)

#### 5. Checking finiteness of number

In [43]:
qfive = np.array([np.inf, 2, np.nan ,4 ,-np.inf])
np.isfinite(qfive)

array([False,  True, False,  True, False])

#### 6. Checking elementwise positive infinity or negetive infinity 

In [48]:
qsix1 = np.array([np.inf, 2, np.nan ,4 ,-np.inf])
np.isneginf(qsix1)

array([False, False, False, False,  True])

In [50]:
np.isposinf(qsix1)

array([ True, False, False, False, False])

#### 7. Checking elementwise nan value

In [56]:
qseven = np.array([np.inf, 2, np.nan ,4 ,-np.inf])
np.isnan(qseven)

array([False, False,  True, False, False])

#### 8. element-wise complex number, real number, saclar type...

In [111]:
qeight2 = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
qeight = np.array([4j, 5, 7, 9, 11, 9+3j])



In [113]:
np.iscomplex(qeight2)

array([ True, False, False, False, False,  True])

In [117]:
np.isscalar(qeight2)

False

In [83]:
np.isreal(qeight2)

array([False,  True,  True,  True,  True, False])

#### 9. Element Wise compareson

In [89]:
one = np.array([1, 5, 6, 2, 9])
two = np.array([2, 4, 6, 1, 8])
one < two, one <= two, one >= two, one > two

(array([ True, False, False, False, False]),
 array([ True, False,  True, False, False]),
 array([False,  True,  True,  True,  True]),
 array([False,  True, False,  True,  True]))

#### 10. determine size of arr

In [95]:
arr = np.array([1, 7, 13, 105])
arr.nbytes

16

#### 11. 10 zeros, 10 ones, 10 fives

In [97]:
np.zeros(10), np.ones(10), np.ones(10) * 5

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]))

#### 12. integers from 30 to 70


In [104]:
np.arange(30, 71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

#### 13. Even numbers in range 30, 70

In [121]:
np.arange(30, 71, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#### 14. 3x3 identity matrix

In [131]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 15. RANDOM NUMBER BETWEEN 0 AND 1

In [139]:
np.random.rand(1)

array([0.73369289])

#### 16. 15 random numbers in normal destribution

In [143]:
np.random.randn(15)

array([-0.73998499, -1.68388572,  1.67026673,  0.09520836, -0.10051829,
        0.83872766,  0.39103946,  0.40211391, -0.50421066, -1.69111563,
       -0.38457945,  0.89509655,  0.96328908, -1.09825119, -0.69139662])

#### 17. vector with values 15 to 55 and print with first and last

In [154]:
np.arange(15, 56)[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

#### 18. 3X4 array

In [168]:
np.array([1, 2, 3, 4, 1, 3 ,4, 6, 2, 3, 6, 9]).reshape(3, 4)

array([[1, 2, 3, 4],
       [1, 3, 4, 6],
       [2, 3, 6, 9]])

#### 19. 10 values with values evenly destributed between 5 and 50

In [172]:
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

#### 20. create array and change sign within specific range

In [182]:
arr = np.arange(0, 21)
arr[9:16] *= -1
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

#### 21. random integers, array of length 5, elements within range(0, 10)

In [188]:
np.random.randint(0, 10, 5)

array([1, 1, 9, 8, 0])

#### 22. Multiplying values of two given vectors

In [197]:
vec1 = np.array([2, 3, 5, 7, 9])
vec2 = np.array([1, 2, 1, 3, 9])
vec1 * vec2

array([ 2,  6,  5, 21, 81])

#### 23. 3x4 matrix with values filled with numbers in range(10, 21)

In [204]:
np.arange(10, 22).reshape(3, 4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

#### 24. number of rows and columns of given matrix

In [209]:
np.arange(10, 22).reshape(3, 4).shape

(3, 4)

#### 25. 3x3 identity matrix 

In [217]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 26. 10 x 10 matrix with border 1 and inside 0

In [439]:
arr = np.ones((12, 12))
for i in range(1, 6):
    arr[ i : -i , i : -i, ] = i-1
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 2., 2., 2., 2., 2., 2., 1., 0., 1.],
       [1., 0., 1., 2., 3., 3., 3., 3., 2., 1., 0., 1.],
       [1., 0., 1., 2., 3., 4., 4., 3., 2., 1., 0., 1.],
       [1., 0., 1., 2., 3., 4., 4., 3., 2., 1., 0., 1.],
       [1., 0., 1., 2., 3., 3., 3., 3., 2., 1., 0., 1.],
       [1., 0., 1., 2., 2., 2., 2., 2., 2., 1., 0., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 27. 5 x 5 0 matrix with diagonal elements = 1, 2, 3, 4, 5

In [235]:
np.diagflat([[1, 2, 3, 4, 5]])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 28. 3 x 3 x 3 array with random values

In [244]:
np.random.randint(1, 100, (3, 3, 3))

array([[[38, 10, 75],
        [64, 29, 84],
        [83, 78, 60]],

       [[ 1,  2, 13],
        [38, 92, 58],
        [42, 78, 58]],

       [[55, 23, 51],
        [31, 14,  7],
        [69,  5, 33]]])

#### 29. Inner product

In [301]:
ar1 = np.arange(1, 5)
ar2 = np.arange(6, 10)
ar1, ar2, ar1.dot(ar2)

(array([1, 2, 3, 4]), array([6, 7, 8, 9]), 80)

In [303]:
np.inner(ar1, ar2)

80

#### 30. sort by row and column in ascending order

In [264]:
arr = np.random.randint(10, 100, (5, 5))
arr

array([[35, 34, 98, 33, 69],
       [20, 54, 44, 13, 41],
       [29, 82, 47, 30, 62],
       [81, 72, 83, 45, 76],
       [65, 38, 97, 19, 24]])

In [266]:
np.sort(arr, 0), np.sort(arr, 1)

(array([[20, 34, 44, 13, 24],
        [29, 38, 47, 19, 41],
        [35, 54, 83, 30, 62],
        [65, 72, 97, 33, 69],
        [81, 82, 98, 45, 76]]),
 array([[33, 34, 35, 69, 98],
        [13, 20, 41, 44, 54],
        [29, 30, 47, 62, 82],
        [45, 72, 76, 81, 83],
        [19, 24, 38, 65, 97]]))

#### 31. Extraction 

In [386]:
arr = np.random.randint(10, 50, 10)
arr

array([46, 45, 16, 12, 38, 46, 32, 44, 37, 37])

In [395]:
arr[arr > 30]


array([46, 45, 38, 46, 32, 44, 37, 37])

In [284]:
np.extract(arr > 20, arr)

array([27, 45, 32, 33, 33, 29])

In [286]:
np.extract(arr <= 20, arr)

array([11, 19, 17, 20])

#### 32. Replacement, less than, greater than, equal to

In [345]:
arr = np.random.randint(5, 8, 10)
arr

array([5, 7, 7, 6, 6, 5, 6, 5, 5, 6])

In [397]:
arr = np.random.randint(5, 8, 10)
print(arr)
arr[arr >= 6] = 0
arr

[6 7 6 7 5 6 6 5 6 7]


array([0, 0, 0, 0, 5, 0, 0, 5, 0, 0])

In [405]:
arr = np.random.randint(5, 8, 10)
print(arr)
arr[(arr < 6) | (arr > 6)] = 0
arr

[6 5 6 5 5 6 7 5 6 7]


array([6, 0, 6, 0, 0, 6, 0, 0, 6, 0])

In [347]:
arr_bool = arr > 6
arr_bool

array([False,  True,  True, False, False, False, False, False, False,
       False])

In [355]:
arr[arr_bool] = 0 
arr

array([5, 0, 0, 6, 6, 5, 6, 5, 5, 6])

In [357]:
arr[arr < 6] = 1
arr

array([1, 1, 1, 6, 6, 1, 6, 1, 1, 6])

In [359]:
arr[arr == 6] = 2
arr

array([1, 1, 1, 2, 2, 1, 2, 1, 1, 2])

#### 33. Program to create an array of equal shape and data type of a given array.

In [407]:
arr = np.random.randint(2, 5, 12).reshape(3, 4)
arr.dtype

dtype('int32')

In [421]:
arr2 = np.full_like(arr, 0)
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [429]:
arr1 = np.random.randint(1,11,10).reshape(2,5)
arr1

array([[ 8,  2,  3, 10,  8],
       [ 4,  5,  4, 10,  2]])

In [431]:
newArr = np.empty_like(arr1)
newArr

array([[  4128860,   6029375,   3801155,   5570652,   6619251],
       [  7536754, 917831680,       594, 928382976,       594]])

#### 34. Three dimensional array and setting it to varialbe

In [370]:
arr = np.arange(3 * 4 * 5).reshape(3, 4, 5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

#### 35. Numpy program to multiply two given arrays of same size element by element

In [376]:
arr = np.random.randint(10, 20, 10).reshape(2, 5)
brr = np.random.randint(10, 20, 10).reshape(5, 2)
arr * brr.T

array([[169, 221, 288, 225, 306],
       [266, 160, 180, 272, 192]])