In [1]:
import numpy as np
import random
import math
temp = [random.randint(1, 4) for i in range(5)]
temp2 = [random.randint(1, 4) for i in range(5)]
temp3= [random.randint(1, 4) for i in range(5)]
temp4 = [random.randint(1, 4) for i in range(5)]

In [2]:
arr1 = np.array([temp, temp2])
arr2 = np.array([temp3, temp4])
arr1, arr2

(array([[4, 3, 3, 2, 1],
        [2, 4, 3, 2, 2]]),
 array([[3, 3, 3, 1, 4],
        [1, 2, 2, 3, 1]]))

In [3]:
arr3 = arr1 + arr2
arr3

array([[7, 6, 6, 3, 5],
       [3, 6, 5, 5, 3]])

In [4]:
arr4 = arr1 * arr2
arr4

array([[12,  9,  9,  2,  4],
       [ 2,  8,  6,  6,  2]])

In [5]:
arr5 = arr1 - arr2
arr5

array([[ 1,  0,  0,  1, -3],
       [ 1,  2,  1, -1,  1]])

In [6]:
arr6 = arr1 ** arr2
arr6

array([[64, 27, 27,  2,  1],
       [ 2, 16,  9,  8,  2]])

In [7]:
np.exp(arr1)

array([[54.59815003, 20.08553692, 20.08553692,  7.3890561 ,  2.71828183],
       [ 7.3890561 , 54.59815003, 20.08553692,  7.3890561 ,  7.3890561 ]])

In [15]:
temp = [random.randint(1,5) for i in range(5)]
temp2 = [random.randint(10,45) for i in range(5)]
temp3= [random.randint(1,20) for i in range(5)]
temp4 = [random.randint(11,15) for i in range(5)]

arr1 = np.array([temp,temp2])
arr2= np.array([temp3,temp4])
arr3 = arr1 + arr2
arr3

array([[20, 19, 11, 23,  5],
       [39, 35, 41, 50, 57]])

In [19]:
arr4 = arr1 - arr2
arr4

array([[-14, -11,  -5, -13,  -1],
       [ 13,   9,  15,  24,  27]])

In [21]:
arr5 = arr1*arr2

In [ ]:
arr6 = np