In [23]:
import pandas as pd
import numpy as np

In [29]:
dates = pd.date_range(start = '2024-01-01', periods = 10, freq = 'D')
"""
freq = 'D' -> Day
freq = 'W' -> Week
freq = 'M' -> Month
freq = 'H' -> Hour
"""
dates

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D')

In [25]:
data = np.random.randn(10)
data

array([ 0.58472977, -0.15827741, -0.48313254, -0.1142027 ,  0.46659452,
        0.06892431,  0.57335761, -1.22689937,  1.55068986, -1.81389056])

In [33]:
time_ser = pd.Series(data, index = dates)
time_ser

2024-01-01    0.584730
2024-01-02   -0.158277
2024-01-03   -0.483133
2024-01-04   -0.114203
2024-01-05    0.466595
2024-01-06    0.068924
2024-01-07    0.573358
2024-01-08   -1.226899
2024-01-09    1.550690
2024-01-10   -1.813891
Freq: D, dtype: float64

In [37]:
time_ser['2024-01-05']

0.4665945173183145

In [41]:
time_ser['2024-01-01': '2024-01-05']

2024-01-01    0.584730
2024-01-02   -0.158277
2024-01-03   -0.483133
2024-01-04   -0.114203
2024-01-05    0.466595
Freq: D, dtype: float64

In [45]:
time_ser[time_ser > 0]

2024-01-01    0.584730
2024-01-05    0.466595
2024-01-06    0.068924
2024-01-07    0.573358
2024-01-09    1.550690
dtype: float64

In [47]:
hr_dates =pd.date_range(start = "2024-01-01", periods=  24, freq = 'h')
hr_dates

DatetimeIndex(['2024-01-01 00:00:00', '2024-01-01 01:00:00',
               '2024-01-01 02:00:00', '2024-01-01 03:00:00',
               '2024-01-01 04:00:00', '2024-01-01 05:00:00',
               '2024-01-01 06:00:00', '2024-01-01 07:00:00',
               '2024-01-01 08:00:00', '2024-01-01 09:00:00',
               '2024-01-01 10:00:00', '2024-01-01 11:00:00',
               '2024-01-01 12:00:00', '2024-01-01 13:00:00',
               '2024-01-01 14:00:00', '2024-01-01 15:00:00',
               '2024-01-01 16:00:00', '2024-01-01 17:00:00',
               '2024-01-01 18:00:00', '2024-01-01 19:00:00',
               '2024-01-01 20:00:00', '2024-01-01 21:00:00',
               '2024-01-01 22:00:00', '2024-01-01 23:00:00'],
              dtype='datetime64[ns]', freq='h')

In [49]:
hr_data = np.random.randn(24)
hr_data

array([ 6.80564820e-01,  6.48504472e-01,  3.55367584e-01, -4.61700922e-01,
       -1.39798369e+00,  2.22782472e+00,  1.68491390e+00,  1.09803184e+00,
        5.01132707e-01, -1.12567919e+00, -2.40186168e-01, -1.75608430e-01,
       -1.59329563e-03, -6.65032348e-01, -8.58955739e-01,  5.79630313e-01,
        7.48520524e-01,  6.22844870e-01, -9.12336464e-01, -1.22422750e+00,
        5.54231433e-01,  1.05676695e+00,  2.29067119e-01,  8.07523422e-01])

In [55]:
hr_ser = pd.Series(hr_data, index = hr_dates)
hr_ser

2024-01-01 00:00:00    0.680565
2024-01-01 01:00:00    0.648504
2024-01-01 02:00:00    0.355368
2024-01-01 03:00:00   -0.461701
2024-01-01 04:00:00   -1.397984
2024-01-01 05:00:00    2.227825
2024-01-01 06:00:00    1.684914
2024-01-01 07:00:00    1.098032
2024-01-01 08:00:00    0.501133
2024-01-01 09:00:00   -1.125679
2024-01-01 10:00:00   -0.240186
2024-01-01 11:00:00   -0.175608
2024-01-01 12:00:00   -0.001593
2024-01-01 13:00:00   -0.665032
2024-01-01 14:00:00   -0.858956
2024-01-01 15:00:00    0.579630
2024-01-01 16:00:00    0.748521
2024-01-01 17:00:00    0.622845
2024-01-01 18:00:00   -0.912336
2024-01-01 19:00:00   -1.224227
2024-01-01 20:00:00    0.554231
2024-01-01 21:00:00    1.056767
2024-01-01 22:00:00    0.229067
2024-01-01 23:00:00    0.807523
Freq: h, dtype: float64

In [57]:
hr_ser["2024-01-01 15:00:00"]

0.5796303125826041

In [61]:
hr_ser["2024-01-01 07:00:00": "2024-01-01 17:00:00"][hr_ser > 0]

2024-01-01 07:00:00    1.098032
2024-01-01 08:00:00    0.501133
2024-01-01 15:00:00    0.579630
2024-01-01 16:00:00    0.748521
2024-01-01 17:00:00    0.622845
dtype: float64

In [63]:
hr_ser.loc['2024-01-01 18:00:00']

-0.9123364638413907

In [77]:
hr_ser.loc["2024-01-01 09:00:00": "2024-01-01 18:00:00"]

2024-01-01 09:00:00   -1.125679
2024-01-01 10:00:00   -0.240186
2024-01-01 11:00:00   -0.175608
2024-01-01 12:00:00   -0.001593
2024-01-01 13:00:00   -0.665032
2024-01-01 14:00:00   -0.858956
2024-01-01 15:00:00    0.579630
2024-01-01 16:00:00    0.748521
2024-01-01 17:00:00    0.622845
2024-01-01 18:00:00   -0.912336
Freq: h, dtype: float64

In [67]:
hr_ser[["2024-01-01 07:00:00", "2024-01-01 11:00:00", "2024-01-01 16:00:00"]]

2024-01-01 07:00:00    1.098032
2024-01-01 11:00:00   -0.175608
2024-01-01 16:00:00    0.748521
dtype: float64

In [71]:
hr_ser.iloc[11]

-0.17560842998962958

In [73]:
hr_ser.iloc[2:5]

2024-01-01 02:00:00    0.355368
2024-01-01 03:00:00   -0.461701
2024-01-01 04:00:00   -1.397984
Freq: h, dtype: float64

In [ ]:
hr_ser.iloc[2, 5 ,7, 13]

In [81]:
hr_ser["2024-01-01 04:00:00":"2024-01-01 11:00:00"]

2024-01-01 04:00:00   -1.397984
2024-01-01 05:00:00    2.227825
2024-01-01 06:00:00    1.684914
2024-01-01 07:00:00    1.098032
2024-01-01 08:00:00    0.501133
2024-01-01 09:00:00   -1.125679
2024-01-01 10:00:00   -0.240186
2024-01-01 11:00:00   -0.175608
Freq: h, dtype: float64

In [83]:
hr_ser["2024-01-01 11:00:00" : ]

2024-01-01 11:00:00   -0.175608
2024-01-01 12:00:00   -0.001593
2024-01-01 13:00:00   -0.665032
2024-01-01 14:00:00   -0.858956
2024-01-01 15:00:00    0.579630
2024-01-01 16:00:00    0.748521
2024-01-01 17:00:00    0.622845
2024-01-01 18:00:00   -0.912336
2024-01-01 19:00:00   -1.224227
2024-01-01 20:00:00    0.554231
2024-01-01 21:00:00    1.056767
2024-01-01 22:00:00    0.229067
2024-01-01 23:00:00    0.807523
Freq: h, dtype: float64

In [85]:
hr_ser[: "2024-01-01 04:00:00"]

2024-01-01 00:00:00    0.680565
2024-01-01 01:00:00    0.648504
2024-01-01 02:00:00    0.355368
2024-01-01 03:00:00   -0.461701
2024-01-01 04:00:00   -1.397984
Freq: h, dtype: float64

# part 2

In [90]:
wk_data = time_ser.resample('W').mean()
wk_data

2024-01-07    0.133999
2024-01-14   -0.496700
Freq: W-SUN, dtype: float64

In [96]:
rolling_mean = time_ser.rolling(window = 3).mean()
rolling_mean

2024-01-01         NaN
2024-01-02         NaN
2024-01-03   -0.018893
2024-01-04   -0.251871
2024-01-05   -0.043580
2024-01-06    0.140439
2024-01-07    0.369625
2024-01-08   -0.194872
2024-01-09    0.299049
2024-01-10   -0.496700
Freq: D, dtype: float64

In [98]:
time_ser

2024-01-01    0.584730
2024-01-02   -0.158277
2024-01-03   -0.483133
2024-01-04   -0.114203
2024-01-05    0.466595
2024-01-06    0.068924
2024-01-07    0.573358
2024-01-08   -1.226899
2024-01-09    1.550690
2024-01-10   -1.813891
Freq: D, dtype: float64

In [100]:
time_ser["2024-01-03"] = np.nan
time_ser

2024-01-01    0.584730
2024-01-02   -0.158277
2024-01-03         NaN
2024-01-04   -0.114203
2024-01-05    0.466595
2024-01-06    0.068924
2024-01-07    0.573358
2024-01-08   -1.226899
2024-01-09    1.550690
2024-01-10   -1.813891
Freq: D, dtype: float64

In [102]:
fl_ser = time_ser.ffill()
fl_ser

2024-01-01    0.584730
2024-01-02   -0.158277
2024-01-03   -0.158277
2024-01-04   -0.114203
2024-01-05    0.466595
2024-01-06    0.068924
2024-01-07    0.573358
2024-01-08   -1.226899
2024-01-09    1.550690
2024-01-10   -1.813891
Freq: D, dtype: float64

In [106]:
wk_ser = time_ser.resample("W").mean()
wk_ser

2024-01-07    0.236854
2024-01-14   -0.496700
Freq: W-SUN, dtype: float64

In [108]:
back_fl_ser = time_ser.bfill()
back_fl_ser

2024-01-01    0.584730
2024-01-02   -0.158277
2024-01-03   -0.114203
2024-01-04   -0.114203
2024-01-05    0.466595
2024-01-06    0.068924
2024-01-07    0.573358
2024-01-08   -1.226899
2024-01-09    1.550690
2024-01-10   -1.813891
Freq: D, dtype: float64

In [110]:
interpol = time_ser.interpolate()
interpol

2024-01-01    0.584730
2024-01-02   -0.158277
2024-01-03   -0.136240
2024-01-04   -0.114203
2024-01-05    0.466595
2024-01-06    0.068924
2024-01-07    0.573358
2024-01-08   -1.226899
2024-01-09    1.550690
2024-01-10   -1.813891
Freq: D, dtype: float64

In [114]:
date = pd.date_range(start = "2024-01-01", periods = 10, freq = "D")
data = [1, 2, np.nan, 4, np.nan, 6, 7, np.nan, 9, 10]

In [116]:
time_ser2 = pd.Series(data, index = date)
time_ser2

2024-01-01     1.0
2024-01-02     2.0
2024-01-03     NaN
2024-01-04     4.0
2024-01-05     NaN
2024-01-06     6.0
2024-01-07     7.0
2024-01-08     NaN
2024-01-09     9.0
2024-01-10    10.0
Freq: D, dtype: float64

In [126]:
missing_vals = time_ser2.isna()
missing_vals

2024-01-01    False
2024-01-02    False
2024-01-03     True
2024-01-04    False
2024-01-05     True
2024-01-06    False
2024-01-07    False
2024-01-08     True
2024-01-09    False
2024-01-10    False
Freq: D, dtype: bool

In [128]:
missing_vals.sum()

3

In [132]:
temp = time_ser.index[missing_vals]
temp

DatetimeIndex(['2024-01-03', '2024-01-05', '2024-01-08'], dtype='datetime64[ns]', freq=None)

In [136]:
fld_vals = time_ser2.fillna(0)
fld_vals

2024-01-01     1.0
2024-01-02     2.0
2024-01-03     0.0
2024-01-04     4.0
2024-01-05     0.0
2024-01-06     6.0
2024-01-07     7.0
2024-01-08     0.0
2024-01-09     9.0
2024-01-10    10.0
Freq: D, dtype: float64

In [138]:
drop_vals = time_ser2.dropna()
drop_vals

2024-01-01     1.0
2024-01-02     2.0
2024-01-04     4.0
2024-01-06     6.0
2024-01-07     7.0
2024-01-09     9.0
2024-01-10    10.0
dtype: float64

In [152]:
dates = pd.date_range(start = "2024-01-01", periods = 10, freq = 'd')
dates

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D')

In [154]:
data = np.arange(10)
data


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
time_ser3 = pd.Series(data, index = dates)
time_ser3

2024-01-01    0
2024-01-02    1
2024-01-03    2
2024-01-04    3
2024-01-05    4
2024-01-06    5
2024-01-07    6
2024-01-08    7
2024-01-09    8
2024-01-10    9
Freq: D, dtype: int32

In [158]:
shifted_forward = time_ser3.shift(2)
shifted_forward

2024-01-01    NaN
2024-01-02    NaN
2024-01-03    0.0
2024-01-04    1.0
2024-01-05    2.0
2024-01-06    3.0
2024-01-07    4.0
2024-01-08    5.0
2024-01-09    6.0
2024-01-10    7.0
Freq: D, dtype: float64

In [164]:
shifted_backward = time_ser3.shift(-2)
shifted_backward

2024-01-01    2.0
2024-01-02    3.0
2024-01-03    4.0
2024-01-04    5.0
2024-01-05    6.0
2024-01-06    7.0
2024-01-07    8.0
2024-01-08    9.0
2024-01-09    NaN
2024-01-10    NaN
Freq: D, dtype: float64

In [168]:
shifted_backward.fillna(0)

2024-01-01    2.0
2024-01-02    3.0
2024-01-03    4.0
2024-01-04    5.0
2024-01-05    6.0
2024-01-06    7.0
2024-01-07    8.0
2024-01-08    9.0
2024-01-09    0.0
2024-01-10    0.0
Freq: D, dtype: float64