# Assignment 6

In [1]:
import numpy as np


In [5]:
arr = np.random.randint(50, 100, (5, 5))
arr

array([[93, 54, 89, 53, 85],
       [64, 97, 73, 73, 75],
       [75, 90, 55, 73, 51],
       [72, 50, 55, 70, 69],
       [53, 79, 68, 52, 51]])

In [9]:
arr[1:4, 1:4] = np.zeros((3, 3))
arr

array([[93, 54, 89, 53, 85],
       [64,  0,  0,  0, 75],
       [75,  0,  0,  0, 51],
       [72,  0,  0,  0, 69],
       [53, 79, 68, 52, 51]])

In [11]:
matrix = np.random.randint(50,101,(5,5))
matrix

array([[ 93,  89,  90,  88,  77],
       [ 93, 100,  51,  68,  82],
       [ 54,  51,  87,  78,  81],
       [ 84,  78,  63,  78,  63],
       [ 74,  65,  81,  96,  72]])

matrix[1:4, 1:4] = np.zeros((3,3))
print(matrix)

# Assignment 7


In [27]:
arr = np.random.randint(10, 100, (5, 3))
arr

array([[96, 85, 79],
       [23, 33, 48],
       [43, 58, 85],
       [59, 53, 34],
       [86, 40, 50]])

In [43]:
arr2 = arr.transpose()
#arr2 = arr.T
arr2

array([[96, 23, 43, 59, 86],
       [85, 33, 58, 53, 40],
       [79, 48, 85, 34, 50]])

In [37]:
arr.mean(), arr2.mean()

(58.13333333333333, 58.13333333333333)

# Assignment 8

In [55]:
arr_data = np.loadtxt('numpCSV.txt', delimiter = ',')
arr_data

array([[1. , 2. , 3.5],
       [3.2, 4.7, 3.1],
       [6.2, 6.6, 7.2]])

In [57]:
temp = np.genfromtxt('numpCSV.txt', delimiter = ',', comments = '#')
temp

array([[1. , 2. , 3.5],
       [3.2, 4.7, 3.1],
       [6.2, 6.6, 7.2]])

# Assignment 9

In [60]:
arr = np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [62]:
arr2 = np.sqrt(arr)
arr2

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        ])

In [72]:
arr3 = np.array([arr, arr2])
np.savetxt('square_root_result.csv', arr3, delimiter = ',' )

In [74]:
matrix = np.arange(1,17)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [90]:
matrix2 = np.array([matrix, (np.sqrt(matrix))])

In [96]:
# np.savetxt("sqrtMatrix.txt",np.coloumn_stack((matrix,matrix2)), delimiter = ";")

AttributeError: module 'numpy' has no attribute 'coloumn_stack'

# Assignment 10

In [99]:
matrix1 = np.random.randint(1,100,(4,2))

In [101]:
matrix2 = np.random.randint(1,200,(2,3))

In [103]:
matrixR = np.matmul(matrix1,matrix2)

In [105]:
print(matrix1)

[[18 62]
 [95 47]
 [15 24]
 [23 22]]


In [107]:
print(matrix2)

[[  3 160  84]
 [107  99 127]]


In [111]:
print(matrixR)

[[ 6688  9018  9386]
 [ 5314 19853 13949]
 [ 2613  4776  4308]
 [ 2423  5858  4726]]


In [113]:
print(matrixR.T)

[[ 6688  5314  2613  2423]
 [ 9018 19853  4776  5858]
 [ 9386 13949  4308  4726]]


In [115]:
np.matmul(np.random.randint(1, 20, (4, 2)) , np.random.randint(1, 20, (2, 3))).T

array([[ 39, 287,  72,  75],
       [145, 387, 176, 233],
       [ 83, 305, 112, 139]])

# Assignment HW

In [120]:
matrix = np.random.randint(0,100,(3,3))
matrix

array([[29, 23, 29],
       [27, 94, 59],
       [60, 58, 19]])

In [126]:
eigen = np.linalg.eig(matrix)
eigen

EigResult(eigenvalues=array([142.32100913,  25.80754152, -26.12855066]), eigenvectors=array([[-0.29578594, -0.65365159, -0.31141016],
       [-0.80092806,  0.62633312, -0.36161358],
       [-0.52060054, -0.42478987,  0.87878287]]))

In [154]:
eigenValues = eigen[0]
eigenValues

array([142.32100913,  25.80754152, -26.12855066])

In [156]:
eigenVectors = eigen[1]
eigenVectors

array([[-0.29578594, -0.65365159, -0.31141016],
       [-0.80092806,  0.62633312, -0.36161358],
       [-0.52060054, -0.42478987,  0.87878287]])

In [168]:
newMatrix= np.zeros((3,4))
newMatrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [182]:
newMatrix[:: , :3:] = eigenVectors
newMatrix[::, 3::] = eigenValues.reshape((3, 1))
newMatrix

array([[ -0.29578594,  -0.65365159,  -0.31141016, 142.32100913],
       [ -0.80092806,   0.62633312,  -0.36161358,  25.80754152],
       [ -0.52060054,  -0.42478987,   0.87878287, -26.12855066]])

In [210]:
# np.savetxt('eigenVectorsAndValues.csv', np.array([np.array([eigenValues]), eigenVectors]), delimiter = ';')
np.savetxt('eigenVectorsAndValues.csv', newMatrix, fmt='%30.18e', delimiter=' ', newline='\n', header=f'Eigen Vector, {"\t"*22} Eigen Value', footer='', comments='# ', encoding=None)

In [ ]:
newMatrix= np.array([eigenVectors, eigenValues[i]] for i in range(0-3))
newMatrix