In [3]:
# Assignment 1
import numpy as np
arr = np.arange(0, 20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
# Assignment 2
arr2 = arr.reshape((4, 5))
print(arr2, "\n")
arr3 = arr2.reshape(20)
print(arr3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
# Assignment 3
arr4 = np.random.randint(1, 10, (3,3))
print(arr4)
arr4.transpose()

[[3 2 4]
 [3 2 8]
 [2 1 7]]


array([[3, 3, 2],
       [2, 2, 1],
       [4, 8, 7]])