Properties of Dataset:
1. Dimensions( number of dimensions, numpy property - ndim)
2. shape(size of each dimension, numpy property - shape)
3. size()
4. datatype()

In [5]:
import numpy as np
array_1d = np.array([2, 3 ,4])
print (array_1d.ndim,
array_1d.shape,
array_1d.size,
array_1d.dtype)

1 (3,) 3 int32


In [9]:
arr = np.array([[2, 3, 5], [2, 3, 3]])
print(f"ndim: {arr.ndim}\nshape: {arr.shape}\nsize: {arr.size}\ndtype: {arr.dtype}")

ndim: 2
shape: (2, 3)
size: 6
dtype: int32


In [27]:
float_array = np.linspace(0, 7, 6)
int_array = np.arange(2, 8)
bool_array = np.array([True, False, False, True, False, True])

print(float_array.itemsize)
print(int_array.itemsize)
print(bool_array.itemsize)

8
4
1


In [29]:
print(float_array.nbytes)
print(int_array.nbytes)
print(bool_array.nbytes)

48
24
6


# *Data Transformation*

In [40]:
array1d = np.arange(10)
print("1d array:", array1d)


1d array: [0 1 2 3 4 5 6 7 8 9]


In [44]:
print("First five elements: ", array1d[:5])

First five elements:  [0 1 2 3 4]


In [46]:
print("Every other element", array1d[::2])

Every other element [0 2 4 6 8]


In [48]:
print("Array reversed:", array1d[::-1])

Array reversed: [9 8 7 6 5 4 3 2 1 0]


In [50]:
array2d = np.arange(10,22).reshape(3,4)
print(array2d)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [52]:
print("Element in 2nd row and 3rd", array2d[2,3])

Element in 2nd row and 3rd 21


In [56]:
print(array2d[0,:])

[10 11 12 13]


In [58]:
print(array2d[:,2])

[12 16 20]


In [60]:
print(array2d[:2,-2:])

[[12 13]
 [16 17]]


In [62]:
print(array2d[::2,::2])

[[10 12]
 [18 20]]


In [66]:
array3d = np.random.randint(1,21, (2,3,4))
array3d

array([[[ 4, 12, 13, 19],
        [ 7, 20,  4, 19],
        [19, 20,  8, 13]],

       [[10, 14, 13, 12],
        [14, 11,  4,  1],
        [19, 18,  9, 12]]])

In [68]:
array3d[0, 1, 2]

4

In [70]:
array3d[1, :, :]

array([[10, 14, 13, 12],
       [14, 11,  4,  1],
       [19, 18,  9, 12]])

In [72]:
array3d[:, :2, :3]

array([[[ 4, 12, 13],
        [ 7, 20,  4]],

       [[10, 14, 13],
        [14, 11,  4]]])