In [1]:
import numpy as np
import random

In [2]:
sales = np.array([random.randint(20, 100) for _ in range(10)])
sales

array([47, 76, 30, 30, 50, 58, 72, 30, 59, 70])

In [3]:
fifth_day_sales = sales[4]
fifth_day_sales

50

In [4]:
first_five_days = sales[:5]
first_five_days

array([47, 76, 30, 30, 50])

In [5]:
last_three_days = sales[-3:]
last_three_days

array([30, 59, 70])

In [6]:
increased_sales = sales + np.array([10 for _ in range(10)])
increased_sales

array([57, 86, 40, 40, 60, 68, 82, 40, 69, 80])

In [7]:
after_discount_application = sales - (sales / 10)
after_discount_application

array([42.3, 68.4, 27. , 27. , 45. , 52.2, 64.8, 27. , 53.1, 63. ])

In [8]:
total_sales = sales.sum()
total_sales

522

In [9]:
avg_sales = sales.sum()/ len(sales)
avg_sales

52.2

In [10]:
max, min = sales.max(), sales.min()
max, min

(76, 30)

In [11]:
new_array = sales.reshape((2, 5))
new_array


array([[47, 76, 30, 30, 50],
       [58, 72, 30, 59, 70]])

In [12]:
named_row_sum = np.sum(new_array, axis = 1)
named_row_sum

array([233, 289])

In [13]:
sales_more_than_20 = sales[sales > 20]
sales_more_than_20

array([47, 76, 30, 30, 50, 58, 72, 30, 59, 70])

In [14]:
boolean_array = sales > 40
boolean_array

array([ True,  True, False, False,  True,  True,  True, False,  True,
        True])

In [15]:
returns = np.random.randint(10, 40, 10)
returns

array([36, 23, 15, 30, 10, 38, 27, 25, 14, 27])

In [16]:
net_sales = sales - returns
net_sales

array([11, 53, 15,  0, 40, 20, 45,  5, 45, 43])